---
Name: silvercart_print_routes
---
SilverStripe\Control\Director:
  rules:
    'silvercart-print/$DataObjectName/$DataObjectID': SilverCart\View\Printer\PrinterController
    'silvercart-print-inline/$DataObjectName/$DataObjectID': SilverCart\View\Printer\PrinterController
    'silvercart-print-many/$DataObjectName/$DataObjectID': SilverCart\View\Printer\PrinterController
---
Name: silvercart_action_routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'sc-action//$Action/$ID/$OtherID': SilverCart\Control\ActionHandler
---
Name: silvercart_example_data_routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'example-data//$Action/$ID/$OtherID': SilverCart\Admin\Dev\ExampleDataController
---
Name: silvercart_task_routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'silvercart/tasks/assign-product-keywords': SilverCart\Dev\Tasks\AssignProductKeywordsTask
    'silvercart/tasks/reset-stock': SilverCart\Dev\Tasks\ResetStockTask
    'silvercart/tasks/delete-customers': SilverCart\Dev\Tasks\DeleteCustomersTask